### ISSUE TITLE
E2E tests with Detox

### ISSUE THREAD

**Issue by alvrba** [graasp/graasp-mobile-builder#18]

**Comment by pyphilia** [comment]
Or could be another framework working with React Native.

**Comment by spaenleh** [comment]
From the [React Native - Testing](https://reactnative.dev/docs/testing-overview#end-to-end-tests) page: 
- [Detox](https://github.com/wix/detox/)
- [Appium](https://appium.io/docs/en/2.1/)
- [Maestro](https://maestro.mobile.dev/)
