### ISSUE TITLE
refresh folder when item in it has been deleted

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-mobile-builder#74]
Version: 1.1.3 (1)

Platform: iOS

Issue: When deleting an item from a folder, the folder does not refresh and still shows the item after deleting. If you leave the folder and come back, the item is no longer there.

**Comment by alvrba** [comment]
@juancarlosfarah could you test to change the name of an item and see if the item name (in the list, not in the pop-up) is updated automatically without refreshing?
