### ISSUE TITLE
update "Perform" and "Compose" labels in the share menu

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-mobile-builder#75]
Version: 1.1.3 (1)

Platform: iOS

Update Perform and Compose labels in the Share menu.

Should read: "Builder" and "Player"

**Comment by juancarlosfarah** [comment]
![IMG_2908](https://github.com/graasp/graasp-mobile-builder/assets/1707188/8c6e4d4d-bae5-41a5-8694-d87a235c1ca8)

**Comment by alvrba** [comment]
Updated also all constants to Builder and Player
