### ISSUE TITLE
update help link

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-mobile-builder#87]
Help link should direct to page on Graasp.org.

@pyphilia @spaenleh, please specify where.

**Comment by alvrba** [comment]
@pyphilia @spaenleh Do you know the correct link for help?

**Comment by spaenleh** [comment]
There currently is not specific "Help" page on either graasp.org, or association.graasp.org
But we can redirect to the FAQ https://association.graasp.org/#faq or simply an email to contact [at] graasp.org

We might create a help page later, information displayed there still needs to be defined. Suggestions welcome.
